export { portalService } from '../portal';
export { tenantService } from './tenant.service';
export { scenariosService } from './scenarios.service';
export { disciplinesService } from './disciplines.service';
export { entrenamientosService } from './entrenamientos.service';
export { planesService } from './planes.service';
export { suscripcionesService } from './suscripciones.service';
export { pagosService } from './pagos.service';
export { asistenciasService } from './asistencias.service';
